---
- name: Create RPM repo configuration
  template:
    src: templates/powerdns.repo.j2
    dest: "{{ powerdns_repo_config }}"
    force: "{{ force | default(false) | bool }}"
  register: r

- name: Install PowerDNS RPMs
  yum:
    name: "{{ powerdns_packages }}"
    state: "{{ r.changed | ternary('latest', 'present') }}"
    allow_downgrade: True
    lock_timeout: 300

- name: Merge custom config
  include_role: name=common tasks_from="implicitly-import-overrides.yml"
  vars:
    base: "{{ powerdns_config }}"
    varname: __config
    prefix: ''
    name: powerdns

- name: Update {{ powerdns_config_file }}
  lineinfile:
    path: "{{ powerdns_config_file }}"
    regexp: '^\s*{{ item.key | regex_escape() }}\s*='
    line: '{{ item.key | string }}={{ item.value }}'
    group: "{{ powerdns_owner }}"
    mode: 0640
  loop: "{{ __config | dict2items }}"
  notify: Restart PowerDNS

- name: Remove conflicting module definitions
  lineinfile:
    path: "{{ powerdns_config_file }}"
    regexp: '^\s*g{{ item }}-'
    state: absent
  when: item != powerdns_driver
  with_items: "{{ powerdns_available_drivers }}"

- name: Set PowerDNS driver credentials
  lineinfile:
    path: "{{ powerdns_config_file }}"
    regexp: '^\s*g{{powerdns_driver}}-{{ item.key | regex_escape() }}\s*='
    line: 'g{{powerdns_driver}}-{{ item.key | string }}={{ item.value }}'
  with_dict: "{{ powerdns_driver_config }}"
  notify: Restart PowerDNS

- name: Create PowerDNS configuration directory
  file:
    path: "{{ powerdns_local_dir }}"
    state: "{{ powerdns_enabled | ternary('directory', 'absent') }}"
    owner: "root"
    group: "{{ powerdns_owner }}"
    mode: 0750

- name: Setup database
  include_tasks: "setup-{{ powerdns_driver }}.yml"
- name: Populate supermaster configuration
  include_tasks: "setup-slave.yml"
  when: '"ip" in powerdns_supermaster and powerdns_supermaster.ip != None'

- name: Enable PowerDNS
  systemd:
    name: pdns
    state: started
    enabled: yes

- name: Record PowerDNS version
  include_role: name=common tasks_from=record-runtime-setting.yml
  vars:
    setting: powerdns_version
