---
- name: Verify {{ powerdns_db_user }} user exists
  postgresql_user:
    name: "{{ powerdns_db_user }}"
    encrypted: yes
    password: "{{ __powerdns_db_password}}"
    state: present
    login_user: root
  register: user_exists
  notify: Restart PowerDNS

- name: Verify {{ powerdns_db_name }} database exists
  postgresql_db:
    name: "{{ powerdns_db_name}}"
    owner: "{{ powerdns_db_user }}"
    template: template1
    state: present
    login_user: root
  register: db_exists

- name: Create {{ powerdns_db_name }} database
  postgresql_db:
    name: "{{ powerdns_db_name}}"
    state: restore
    target: "{{ role_path }}/files/pgsql-{{ powerdns_version }}.sql"
    owner: "{{ powerdns_db_user }}"
    login_password: "{{ __powerdns_db_password }}"
    login_user: "{{powerdns_db_user}}"
    login_host: 127.0.0.1
  when: db_exists.changed
  notify: Restart PowerDNS
