---
- name: Create RPM repo configuration
  template:
    src: templates/powerdns.repo.j2
    dest: "{{ powerdns_repo_config }}"

- name: Install PowerDNS RPMs
  yum:
    name: "{{ powerdns_packages }}"
    state: present
    lock_timeout: 300

- name: Merge custom config
  include_role: name=common tasks_from="implicitly-import-overrides.yml"
  vars:
    base: "{{ powerdns_config }}"
    varname: __config
    prefix: ''
    name: powerdns

- name: Update {{ powerdns_config_file }}
  lineinfile:
    path: "{{ powerdns_config_file }}"
    regexp: '^\s*{{ item.key | regex_escape() }}\s*='
    line: '{{ item.key | string }}={{ item.value }}'
  loop: "{{ powerdns_config | dict2items }}"
  notify: Restart PowerDNS

- name: Set PowerDNS driver credentials
  lineinfile:
    path: "{{ powerdns_config_file }}"
    regexp: '^\s*g{{powerdns_driver}}-{{ item.key | regex_escape() }}\s*='
    line: 'g{{powerdns_driver}}-{{ item.key | string }}={{ item.value }}'
  with_dict: "{{ powerdns_driver_config }}"
  notify: Restart PowerDNS

- name: Create PowerDNS configuration directory
  file:
    path: "{{ powerdns_local_dir }}"
    state: "{{ powerdns_enabled | ternary('directory', 'absent') }}"
    owner: "root"
    group: "root"
    mode: 0700

- name: Setup database
  include_tasks: "setup-{{ powerdns_driver }}.yml"

- name: Enable PowerDNS
  systemd:
    name: pdns
    state: started
    enabled: yes
